# Generated by Django 4.1.4 on 2022-12-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charityinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('district_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=15)),
                ('extra_info', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'charityinfo',
            },
        ),
    ]
