# Generated by Django 4.1.4 on 2022-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityinformation',
            name='open_hours',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='charityinformation',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='charityinformation',
            name='extra_info',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
