# Generated by Django 4.1.4 on 2022-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinderapp', '0002_charityinformation_open_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityinformation',
            name='extra_info',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='charityinformation',
            name='open_hours',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='charityinformation',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
